### PR TITLE
Remove tptoggle check on the sender itself

### PR DESCRIPTION
**Pull request by lululombard**
Right now, if a user toggles their TP, this player is unable to send any request.

### CODE REVIEW

**Comment by Narimm** [comment]
At this stage this  changes a behaviour that has become expected on atleast many servers...you will need to change the PR so that this is a toggled behaviour and by default its toggled off

**Comment by lululombard** [comment]
I updated my repo, not sure how to re-submit changes.

**Comment by lululombard** [comment]
Btw this is still waiting :p

**Comment by lululombard** [comment]
It's been 11 months...

**Pull request closed without merging**
